# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-25 22:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='author',
            field=models.ManyToManyField(to='reviews.Author'),
        ),
    ]
