# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-27 16:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_paper_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paper_cluster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_id', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='paper',
            name='cluster',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='reviews.Paper_cluster'),
        ),
    ]
